import React from 'react'

function King() {
  return (
    <div>King
        <h4 className="decrp">
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Non, amet! Quaerat soluta fugit ipsum quia, perspiciatis ipsa voluptatum excepturi praesentium iste vitae natus provident unde. Officiis expedita voluptatibus pariatur provident consequuntur ipsam mollitia distinctio excepturi qui, tempore corrupti eaque animi rem incidunt voluptatem molestias! Quos fugit corrupti perspiciatis. Cumque minus illo quasi similique aliquam, accusamus tempora ullam doloremque commodi iure quam perferendis inventore consectetur saepe dignissimos ipsam, ipsum sint dolores omnis voluptatibus explicabo autem atque. Odio impedit dolorem sint facere quam error illo ratione voluptates alias, harum quasi sequi recusandae maiores atque. Consequuntur saepe nostrum rerum! Magni dolore neque excepturi officiis impedit similique nemo, repellendus omnis, culpa sequi quam vel minima asperiores placeat fugit doloremque nisi quae. Aut odit eos, ipsum recusandae veritatis optio minima repellat suscipit, voluptas harum explicabo necessitatibus unde quasi! Itaque, numquam architecto ipsam omnis exercitationem velit, animi quam sit nobis commodi magnam maiores est dolor veritatis nisi expedita eius sint assumenda error ratione? Nostrum delectus non ab veniam dolorum earum numquam laborum maxime deserunt dolor molestias at est distinctio unde mollitia, ut officia illum sequi minima neque quos, commodi repellendus? Harum quos odit facilis non corporis culpa saepe unde sequi cum dolores, eos reprehenderit sunt natus, beatae laborum quaerat molestiae iure similique esse suscipit magni velit distinctio aut? A ea eos, esse expedita autem cum soluta repudiandae amet rerum distinctio incidunt pariatur porro rem asperiores exercitationem sint, aperiam est sunt delectus perspiciatis sapiente voluptatem, optio atque adipisci! Soluta distinctio accusantium et ipsa numquam mollitia necessitatibus, at sed nam culpa repellat. Minus consequatur, quis illum debitis fugiat perferendis commodi? Labore exercitationem sapiente voluptatum est eius temporibus fuga adipisci hic assumenda molestias, magni incidunt facilis et inventore fugiat eos, autem culpa libero porro eum. Officiis maxime blanditiis, consectetur odio saepe aliquam asperiores. In obcaecati velit recusandae porro voluptatem!
        </h4>
    </div>
  )
}

export default King